In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder

In [2]:
#load dataset
health_dataset=pd.read_csv('health_dataset.csv')
print(health_dataset)

     Gender Smoking Alcohol_Consumption Exercise_Frequency Blood_Pressure  \
0    Female      No            Moderate              Never         Normal
1     Other     Yes                 NaN              Never         Normal
2      Male     Yes               Heavy              Daily           High
3      Male     Yes               Heavy              Daily         Normal
4      Male      No            Moderate              Often           High
..      ...     ...                 ...                ...            ...
995  Female      No               Heavy              Daily         Normal
996  Female      No               Heavy             Rarely         Normal
997  Female      No                 NaN             Rarely            NaN
998    Male     Yes               Heavy              Never           High
999    Male      No            Moderate             Rarely           High

    Cholesterol_Level Stress_Level   Age   BMI  Heart_Rate  Sleep_Hours  \
0          Borderline         High  90.0  16.6       119.0          3.6
1              Normal          Low  20.0  29.9        69.0          9.9
2                High          Low  52.0  33.5        54.0          8.5
3                High          Low  15.0  20.3        72.0          9.5
4                High       Medium  60.0  36.0        58.0          4.4
..                ...          ...   ...   ...         ...          ...
995        Borderline       Medium  70.0  21.7        95.0          9.3
996        Borderline          Low  61.0  29.8        80.0          3.8
997              High          Low  40.0  33.0        81.0          4.2
998            Normal         High  94.0  38.5        81.0          6.0
999              High          Low  33.0  37.0         NaN          3.9

     Blood_Sugar_Level Medication_Use Family_History Illness
0                143.6            NaN             No     Yes
1                121.8            NaN            Yes      No
2                107.0            NaN            Yes     Yes
3                 92.1            NaN             No     Yes
4                113.6            NaN             No     Yes
..                 ...            ...            ...     ...
995              187.6        Regular             No     Yes
996              114.3        Regular            Yes     Yes
997              119.0        Regular             No      No
998              187.8     Occasional            Yes      No
999              138.9            NaN            Yes     Yes

[1000 rows x 15 columns]

In [3]:
# check first 20 data
health_dataset.head(20)

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,NaN,No,Yes
1,Other,Yes,NaN,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,NaN,Yes,No
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,NaN,Yes,Yes
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,NaN,No,Yes
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,NaN,No,Yes
5,Male,No,NaN,Daily,Low,High,High,53.0,15.8,107.0,9.7,149.0,Occasional,No,No
6,Male,Yes,NaN,Daily,Low,Borderline,Low,39.0,36.1,108.0,4.0,144.9,Occasional,Yes,Yes
7,Male,No,NaN,Daily,Normal,Borderline,High,25.0,26.5,103.0,6.6,91.3,Occasional,Yes,Yes
8,Male,No,Moderate,Never,High,Borderline,Medium,79.0,20.4,95.0,8.8,86.2,Occasional,No,Yes
9,Female,Yes,NaN,Never,High,High,Medium,91.0,18.3,71.0,5.4,73.5,Regular,No,No
10,Other,Yes,Moderate,Never,Low,Borderline,Low,64.0,38.8,113.0,6.0,71.6,NaN,Yes,Yes
11,Male,No,Moderate,Daily,Low,Borderline,Low,99.0,16.8,57.0,3.9,184.4,Regular,No,Yes
12,Female,Yes,Moderate,Never,High,Normal,High,73.0,20.0,69.0,3.9,75.9,NaN,No,Yes
13,Female,No,Heavy,Daily,Normal,Normal,Low,63.0,23.7,100.0,7.3,165.1,NaN,Yes,Yes
14,Other,No,NaN,Never,Low,Borderline,High,42.0,30.5,88.0,7.7,183.4,Regular,No,No
15,Male,No,NaN,Never,Normal,Normal,Low,16.0,28.6,86.0,8.4,82.7,NaN,Yes,Yes
16,Other,No,Moderate,Rarely,Normal,Normal,High,58.0,18.1,99.0,6.9,126.7,Regular,Yes,No
17,Male,NaN,Moderate,Often,Low,Borderline,High,22.0,22.2,83.0,7.5,195.1,Regular,Yes,No
18,Female,Yes,NaN,Daily,Normal,Borderline,High,6.0,21.0,82.0,3.1,178.4,NaN,No,No
19,Female,Yes,Moderate,Rarely,Normal,Borderline,High,43.0,20.3,80.0,4.1,133.7,NaN,No,Yes

In [4]:
## check last 20 data
health_dataset.tail(20)

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
980,Other,Yes,NaN,Daily,Low,Normal,Low,NaN,24.9,82.0,9.6,187.5,Occasional,No,No
981,Male,Yes,NaN,Never,Normal,Normal,High,56.0,20.0,60.0,9.5,148.3,NaN,Yes,No
982,Female,Yes,NaN,Rarely,Normal,High,Medium,94.0,25.6,69.0,5.7,134.1,NaN,No,No
983,Female,Yes,NaN,Daily,High,High,Medium,11.0,24.6,73.0,3.6,172.1,Occasional,No,Yes
984,Male,Yes,NaN,Rarely,High,High,High,4.0,37.9,113.0,4.2,193.2,NaN,Yes,No
985,Other,No,NaN,Daily,High,Borderline,High,49.0,34.0,114.0,3.4,116.3,Occasional,Yes,No
986,Male,No,Heavy,Daily,Low,High,High,41.0,27.6,66.0,3.7,102.5,NaN,No,No
987,Male,No,Heavy,Often,Normal,High,Low,11.0,39.7,110.0,4.3,150.1,NaN,Yes,No
988,Other,No,Heavy,Rarely,Low,Normal,Medium,17.0,26.6,64.0,5.4,134.9,NaN,No,No
989,Other,Yes,Heavy,Never,Normal,Normal,High,65.0,16.5,100.0,6.8,198.6,Regular,Yes,No
990,Female,Yes,NaN,Often,Low,High,Medium,73.0,21.6,76.0,8.0,130.1,Regular,No,No
991,Other,No,Heavy,Often,High,High,Low,78.0,25.9,110.0,4.5,79.7,Occasional,Yes,No
992,Female,No,NaN,Never,High,Normal,Low,93.0,18.9,107.0,7.7,197.1,NaN,Yes,No
993,Other,Yes,Heavy,Often,High,High,Low,16.0,38.7,80.0,7.9,179.7,Occasional,Yes,No
994,Male,No,Moderate,Daily,Low,Borderline,Low,67.0,34.2,61.0,6.9,93.2,Regular,Yes,No
995,Female,No,Heavy,Daily,Normal,Borderline,Medium,70.0,21.7,95.0,9.3,187.6,Regular,No,Yes
996,Female,No,Heavy,Rarely,Normal,Borderline,Low,61.0,29.8,80.0,3.8,114.3,Regular,Yes,Yes
997,Female,No,NaN,Rarely,NaN,High,Low,40.0,33.0,81.0,4.2,119.0,Regular,No,No
998,Male,Yes,Heavy,Never,High,Normal,High,94.0,38.5,81.0,6.0,187.8,Occasional,Yes,No
999,Male,No,Moderate,Rarely,High,High,Low,33.0,37.0,NaN,3.9,138.9,NaN,Yes,Yes

In [5]:
# print entire dataset 
print(health_dataset.to_string())

     Gender Smoking Alcohol_Consumption Exercise_Frequency Blood_Pressure Cholesterol_Level Stress_Level   Age   BMI  Heart_Rate  Sleep_Hours  Blood_Sugar_Level Medication_Use Family_History Illness
0    Female      No            Moderate              Never         Normal        Borderline         High  90.0  16.6       119.0          3.6              143.6            NaN             No     Yes
1     Other     Yes                 NaN              Never         Normal            Normal          Low  20.0  29.9        69.0          9.9              121.8            NaN            Yes      No
2      Male     Yes               Heavy              Daily           High              High          Low  52.0  33.5        54.0          8.5              107.0            NaN            Yes     Yes
3      Male     Yes               Heavy              Daily         Normal              High          Low  15.0  20.3        72.0          9.5               92.1            NaN             No     Yes
4      Male      No            Moderate              Often           High              High       Medium  60.0  36.0        58.0          4.4              113.6            NaN             No     Yes
5      Male      No                 NaN              Daily            Low              High         High  53.0  15.8       107.0          9.7              149.0     Occasional             No      No
6      Male     Yes                 NaN              Daily            Low        Borderline          Low  39.0  36.1       108.0          4.0              144.9     Occasional            Yes     Yes
7      Male      No                 NaN              Daily         Normal        Borderline         High  25.0  26.5       103.0          6.6               91.3     Occasional            Yes     Yes
8      Male      No            Moderate              Never           High        Borderline       Medium  79.0  20.4        95.0          8.8               86.2     Occasional             No     Yes
9    Female     Yes                 NaN              Never           High              High       Medium  91.0  18.3        71.0          5.4               73.5        Regular             No      No
10    Other     Yes            Moderate              Never            Low        Borderline          Low  64.0  38.8       113.0          6.0               71.6            NaN            Yes     Yes
11     Male      No            Moderate              Daily            Low        Borderline          Low  99.0  16.8        57.0          3.9              184.4        Regular             No     Yes
12   Female     Yes            Moderate              Never           High            Normal         High  73.0  20.0        69.0          3.9               75.9            NaN             No     Yes
13   Female      No               Heavy              Daily         Normal            Normal          Low  63.0  23.7       100.0          7.3              165.1            NaN            Yes     Yes
14    Other      No                 NaN              Never            Low        Borderline         High  42.0  30.5        88.0          7.7              183.4        Regular             No      No
15     Male      No                 NaN              Never         Normal            Normal          Low  16.0  28.6        86.0          8.4               82.7            NaN            Yes     Yes
16    Other      No            Moderate             Rarely         Normal            Normal         High  58.0  18.1        99.0          6.9              126.7        Regular            Yes      No
17     Male     NaN            Moderate              Often            Low        Borderline         High  22.0  22.2        83.0          7.5              195.1        Regular            Yes      No
18   Female     Yes                 NaN              Daily         Normal        Borderline         High   6.0  21.0        82.0          3.1              178.4            NaN             No      No
19   Female     Yes            Moderate             Rarely         Normal        Borderline         High  43.0  20.3        80.0          4.1              133.7            NaN             No     Yes
20   Female     Yes                 NaN              Never           High        Borderline       Medium  52.0  25.3       103.0          9.9              169.1            NaN             No      No
21   Female      No               Heavy              Daily         Normal              High         High  70.0  32.6        93.0          3.5              178.3     Occasional             No     Yes
22    Other      No            Moderate              Never           High              High          Low  78.0  20.4        83.0          7.8              115.2        Regular            Yes      No
23     Male     Yes                 NaN              Often            Low        Borderline       Medium  33.0  24.2       111.0          4.2              186.0        Regular            Yes      No
24     Male      No            Moderate             Rarely            Low            Normal       Medium  45.0  24.8        72.0          8.0              131.2     Occasional             No      No
25    Other      No                 NaN              Often           High        Borderline         High  67.0  39.4        95.0          7.9              138.6        Regular             No      No
26     Male      No                 NaN             Rarely            Low        Borderline       Medium  77.0  38.9       105.0          4.6              200.0        Regular             No      No
27   Female     Yes            Moderate              Never         Normal            Normal         High  77.0  35.0        56.0          4.9              179.6            NaN             No      No
28     Male     Yes               Heavy              Often         Normal              High          Low  15.0  21.0       110.0          7.6              117.0     Occasional            Yes      No
29   Female     Yes                 NaN              Often         Normal        Borderline         High  70.0  16.7        52.0          5.7               71.3            NaN             No      No
30    Other      No                 NaN              Never            Low        Borderline       Medium  95.0  22.9        87.0          4.4              151.4     Occasional            Yes     Yes
31     Male     Yes                 NaN              Often         Normal              High          Low  18.0  21.7        83.0          8.1              161.5            NaN             No     Yes
32    Other     Yes               Heavy              Daily            Low              High         High   1.0  27.6        93.0          4.1              154.6        Regular             No      No
33     Male     Yes               Heavy             Rarely         Normal            Normal          Low   9.0  34.4        79.0          9.0              195.8     Occasional             No      No
34   Female     Yes            Moderate             Rarely           High              High          Low  49.0  36.5        66.0          6.6              182.2     Occasional            Yes      No
35    Other     Yes               Heavy             Rarely            Low              High       Medium  80.0  36.1       108.0          3.7              128.3            NaN             No     Yes
36     Male     Yes            Moderate              Daily            Low              High          Low  11.0  24.0        59.0          7.9               78.2     Occasional            Yes      No
37   Female      No            Moderate             Rarely         Normal            Normal       Medium  69.0  32.2        67.0          6.6              131.9        Regular            Yes     Yes
38    Other      No               Heavy              Never            Low              High          Low  21.0  22.8        94.0          5.1              159.6        Regular             No     Yes
39    Other     Yes            Moderate              Often            Low              High         High  31.0  16.5       108.0          6.0              149.0        Regular            Yes     Yes
40     Male     Yes               Heavy              Daily           High            Normal          Low  83.0  32.5       111.0          5.1              140.0            NaN            Yes     Yes
41     Male      No            Moderate             Rarely           High              High         High   0.0  15.2       108.0          4.8                NaN     Occasional            Yes     Yes
42     Male      No               Heavy              Never         Normal              High         High  53.0  25.2        98.0          4.1              108.2            NaN             No      No
43   Female     Yes               Heavy              Often           High            Normal          Low  57.0  23.2       112.0          5.5              106.1        Regular            Yes      No
44     Male     Yes            Moderate              Often         Normal        Borderline         High  69.0  32.3        81.0          4.8              135.0     Occasional            Yes      No
45    Other     Yes                 NaN              Daily         Normal            Normal          Low  82.0  34.2        59.0          7.8               90.9        Regular             No      No
46    Other     Yes            Moderate              Daily         Normal              High          Low  17.0  22.6        60.0          7.8              114.3     Occasional             No      No
47     Male      No               Heavy              Daily            Low              High         High   5.0  35.3       119.0          6.5              112.1     Occasional            Yes     Yes
48     Male     Yes                 NaN              Never           High              High         High  44.0  22.3       111.0          8.4              146.3            NaN            Yes      No
49    Other     Yes            Moderate              Never         Normal            Normal       Medium  96.0  26.2        96.0          8.9               78.7     Occasional            Yes      No
50   Female     Yes            Moderate              Daily           High              High         High  22.0  33.2        83.0          7.1              177.9        Regular            Yes     Yes
51     Male     Yes            Moderate             Rarely         Normal              High       Medium  22.0  32.3        66.0          7.3              143.1     Occasional             No      No
52     Male      No                 NaN              Often           High            Normal         High  25.0  39.7       103.0          5.0              157.2        Regular             No     Yes
53    Other      No               Heavy              Often           High        Borderline          Low  76.0  20.6        89.0          9.3              161.4            NaN            Yes      No
54     Male      No            Moderate              Never         Normal        Borderline         High   6.0  31.6        68.0          3.2              107.9        Regular             No     Yes
55   Female     Yes            Moderate              Often            Low              High          Low  78.0  30.2       116.0          5.4              131.1     Occasional            Yes      No
56    Other     Yes            Moderate             Rarely           High            Normal          Low  43.0  37.9       102.0          8.1              194.3        Regular             No      No
57     Male      No            Moderate              Often            Low              High          Low  26.0  18.9       113.0          3.6              169.7        Regular             No     Yes
58    Other     Yes            Moderate              Never            Low            Normal       Medium  25.0  33.8        96.0          4.3              196.0     Occasional            Yes     Yes
59     Male     Yes               Heavy              Never         Normal            Normal         High  96.0  29.2        55.0          7.1              167.0        Regular            Yes     Yes
60     Male      No               Heavy             Rarely         Normal        Borderline          Low  78.0  21.9        65.0          6.9               92.8     Occasional            Yes     Yes
61     Male      No            Moderate             Rarely         Normal        Borderline          Low  35.0  26.9        67.0          8.2               78.4            NaN            Yes     Yes
62   Female      No                 NaN              Often           High            Normal       Medium  54.0  23.3       101.0          8.7              145.1        Regular             No     Yes
63   Female      No               Heavy              Often         Normal              High         High  63.0  29.5        97.0          3.9              116.5            NaN             No     Yes
64    Other     Yes                 NaN              Never         Normal        Borderline         High  90.0  37.2        92.0          3.1              105.8        Regular            Yes     Yes
65     Male     Yes               Heavy             Rarely           High              High       Medium  56.0  29.2        88.0          7.8              174.9        Regular             No      No
66     Male      No            Moderate             Rarely           High        Borderline       Medium  68.0  30.8        98.0          5.1              117.7            NaN             No      No
67   Female     Yes               Heavy             Rarely         Normal        Borderline         High  60.0  28.0        61.0          7.4              111.2        Regular            Yes     Yes
68     Male      No            Moderate              Often         Normal              High       Medium   1.0  16.3        59.0          4.1              180.5        Regular            Yes      No
69   Female      No               Heavy             Rarely         Normal        Borderline         High  54.0  20.8       104.0          6.3              180.0            NaN             No      No
70     Male     Yes            Moderate              Never         Normal        Borderline         High  96.0  27.3        50.0          6.5              116.3        Regular            Yes      No
71    Other      No            Moderate              Never            Low              High          Low  79.0  22.8        98.0          7.1              178.2     Occasional            Yes      No
72     Male     Yes            Moderate              Often            Low        Borderline          Low  86.0  19.5        85.0          6.6              180.6        Regular             No     Yes
73     Male     Yes            Moderate              Daily         Normal        Borderline         High  37.0  27.6        70.0          6.5              125.1        Regular             No      No
74   Female     Yes                 NaN              Often            Low        Borderline         High  79.0  23.1        86.0          5.3               78.6        Regular            Yes     Yes
75     Male     Yes            Moderate              Daily           High              High         High  77.0  21.5        73.0          3.5               70.2            NaN             No      No
76     Male      No                 NaN             Rarely            Low            Normal         High  28.0  26.6       104.0          3.6              138.0     Occasional            Yes      No
77   Female     Yes                 NaN              Often            Low              High         High  25.0  18.3        74.0          6.0              114.7     Occasional            Yes      No
78    Other      No            Moderate              Never         Normal            Normal         High  34.0  38.2        56.0          5.5              199.6        Regular             No     Yes
79    Other      No                 NaN             Rarely            Low        Borderline       Medium  78.0  36.7        73.0          6.6              170.4            NaN             No      No
80   Female      No               Heavy              Never            Low            Normal         High  66.0  32.7        60.0          5.1              169.0            NaN            Yes     Yes
81   Female      No            Moderate             Rarely            Low              High       Medium  86.0  17.7        61.0          7.8              194.2     Occasional            Yes      No
82   Female     Yes                 NaN              Often            Low              High       Medium  28.0  34.4        84.0          9.0              185.4            NaN            Yes     Yes
83   Female     Yes            Moderate              Daily           High        Borderline         High  33.0  35.2       112.0          5.1              111.4        Regular             No      No
84   Female      No            Moderate             Rarely         Normal            Normal         High  96.0  34.2       117.0          4.4               91.6        Regular            NaN     Yes
85    Other      No            Moderate              Daily         Normal        Borderline       Medium  40.0  17.8       106.0          3.8              167.0            NaN             No     Yes
86    Other     Yes                 NaN             Rarely           High        Borderline       Medium  40.0  31.1        62.0          7.3              119.2        Regular            Yes      No
87   Female      No               Heavy              Never            Low              High         High  22.0  35.9        72.0          6.1              131.5     Occasional             No     Yes
88     Male     Yes               Heavy              Never           High            Normal         High  70.0  29.4        88.0          4.3              152.0        Regular            Yes      No
89   Female      No                 NaN             Rarely            Low            Normal       Medium   2.0  31.2        61.0          7.6              188.0            NaN             No      No
90     Male     Yes            Moderate              Daily           High            Normal       Medium  57.0  26.5        83.0          4.0              124.5            NaN            Yes      No
91   Female      No                 NaN              Often         Normal            Normal       Medium  31.0  28.2        80.0          6.9              171.8        Regular            Yes      No
92   Female      No                 NaN              Often         Normal        Borderline          Low  30.0  15.9       111.0          6.7              104.9     Occasional            Yes      No
93    Other     Yes                 NaN              Never         Normal        Borderline       Medium  81.0  31.0        62.0          8.1              160.7            NaN            Yes      No
94     Male      No            Moderate              Often            Low              High          Low  42.0  17.0        80.0          3.4               70.2        Regular             No      No
95     Male      No                 NaN              Never            Low        Borderline         High   6.0  25.9        51.0          9.2              183.3        Regular             No      No
96    Other     Yes            Moderate              Often           High        Borderline         High   0.0  22.3        64.0          7.9               73.9     Occasional             No      No
97    Other      No                 NaN             Rarely           High              High       Medium  60.0  28.6       106.0          4.5              162.7        Regular             No      No
98    Other     Yes               Heavy              Never         Normal              High         High  13.0  18.3        83.0          4.3               76.0        Regular             No      No

In [6]:
#check max row 
print(pd.options.display.max_rows)

60

In [7]:
print(health_dataset.head())

   Gender Smoking Alcohol_Consumption Exercise_Frequency Blood_Pressure  \
0  Female      No            Moderate              Never         Normal
1   Other     Yes                 NaN              Never         Normal
2    Male     Yes               Heavy              Daily           High
3    Male     Yes               Heavy              Daily         Normal
4    Male      No            Moderate              Often           High

  Cholesterol_Level Stress_Level   Age   BMI  Heart_Rate  Sleep_Hours  \
0        Borderline         High  90.0  16.6       119.0          3.6
1            Normal          Low  20.0  29.9        69.0          9.9
2              High          Low  52.0  33.5        54.0          8.5
3              High          Low  15.0  20.3        72.0          9.5
4              High       Medium  60.0  36.0        58.0          4.4

   Blood_Sugar_Level Medication_Use Family_History Illness
0              143.6            NaN             No     Yes
1              121.8            NaN            Yes      No
2              107.0            NaN            Yes     Yes
3               92.1            NaN             No     Yes
4              113.6            NaN             No     Yes

In [8]:
print(health_dataset.tail())

     Gender Smoking Alcohol_Consumption Exercise_Frequency Blood_Pressure  \
995  Female      No               Heavy              Daily         Normal
996  Female      No               Heavy             Rarely         Normal
997  Female      No                 NaN             Rarely            NaN
998    Male     Yes               Heavy              Never           High
999    Male      No            Moderate             Rarely           High

    Cholesterol_Level Stress_Level   Age   BMI  Heart_Rate  Sleep_Hours  \
995        Borderline       Medium  70.0  21.7        95.0          9.3
996        Borderline          Low  61.0  29.8        80.0          3.8
997              High          Low  40.0  33.0        81.0          4.2
998            Normal         High  94.0  38.5        81.0          6.0
999              High          Low  33.0  37.0         NaN          3.9

     Blood_Sugar_Level Medication_Use Family_History Illness
995              187.6        Regular             No     Yes
996              114.3        Regular            Yes     Yes
997              119.0        Regular             No      No
998              187.8     Occasional            Yes      No
999              138.9            NaN            Yes     Yes

In [9]:
#information of dataset 
print(health_dataset.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               988 non-null    str
 1   Smoking              993 non-null    str
 2   Alcohol_Consumption  649 non-null    str
 3   Exercise_Frequency   993 non-null    str
 4   Blood_Pressure       990 non-null    str
 5   Cholesterol_Level    993 non-null    str
 6   Stress_Level         995 non-null    str
 7   Age                  992 non-null    float64
 8   BMI                  994 non-null    float64
 9   Heart_Rate           992 non-null    float64
 10  Sleep_Hours          994 non-null    float64
 11  Blood_Sugar_Level    997 non-null    float64
 12  Medication_Use       655 non-null    str
 13  Family_History       995 non-null    str
 14  Illness              1000 non-null   str
dtypes: float64(5), str(10)
memory usage: 117.3 KB
None

In [10]:
# check null values 
health_dataset.isna().sum()

Gender                  12
Smoking                  7
Alcohol_Consumption    351
Exercise_Frequency       7
Blood_Pressure          10
Cholesterol_Level        7
Stress_Level             5
Age                      8
BMI                      6
Heart_Rate               8
Sleep_Hours              6
Blood_Sugar_Level        3
Medication_Use         345
Family_History           5
Illness                  0
dtype: int64

In [11]:
# copy dataset
health_dataset_1=health_dataset.copy()
health_dataset_2=health_dataset.copy() 
health_dataset_3=health_dataset.copy() 
health_dataset_4=health_dataset.copy()
health_dataset_5=health_dataset.copy() 
health_dataset_6=health_dataset.copy()  
health_dataset_7=health_dataset.copy()
health_dataset_8=health_dataset.copy() 
health_dataset_9=health_dataset.copy()  
health_dataset_10=health_dataset.copy()

In [12]:
#check duplicated raw  
print(health_dataset_1.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [13]:
# drop duplicated raw  
health_dataset_1.drop_duplicates(inplace=True)

In [14]:
print(health_dataset_1.to_string())

     Gender Smoking Alcohol_Consumption Exercise_Frequency Blood_Pressure Cholesterol_Level Stress_Level   Age   BMI  Heart_Rate  Sleep_Hours  Blood_Sugar_Level Medication_Use Family_History Illness
0    Female      No            Moderate              Never         Normal        Borderline         High  90.0  16.6       119.0          3.6              143.6            NaN             No     Yes
1     Other     Yes                 NaN              Never         Normal            Normal          Low  20.0  29.9        69.0          9.9              121.8            NaN            Yes      No
2      Male     Yes               Heavy              Daily           High              High          Low  52.0  33.5        54.0          8.5              107.0            NaN            Yes     Yes
3      Male     Yes               Heavy              Daily         Normal              High          Low  15.0  20.3        72.0          9.5               92.1            NaN             No     Yes
4      Male      No            Moderate              Often           High              High       Medium  60.0  36.0        58.0          4.4              113.6            NaN             No     Yes
5      Male      No                 NaN              Daily            Low              High         High  53.0  15.8       107.0          9.7              149.0     Occasional             No      No
6      Male     Yes                 NaN              Daily            Low        Borderline          Low  39.0  36.1       108.0          4.0              144.9     Occasional            Yes     Yes
7      Male      No                 NaN              Daily         Normal        Borderline         High  25.0  26.5       103.0          6.6               91.3     Occasional            Yes     Yes
8      Male      No            Moderate              Never           High        Borderline       Medium  79.0  20.4        95.0          8.8               86.2     Occasional             No     Yes
9    Female     Yes                 NaN              Never           High              High       Medium  91.0  18.3        71.0          5.4               73.5        Regular             No      No
10    Other     Yes            Moderate              Never            Low        Borderline          Low  64.0  38.8       113.0          6.0               71.6            NaN            Yes     Yes
11     Male      No            Moderate              Daily            Low        Borderline          Low  99.0  16.8        57.0          3.9              184.4        Regular             No     Yes
12   Female     Yes            Moderate              Never           High            Normal         High  73.0  20.0        69.0          3.9               75.9            NaN             No     Yes
13   Female      No               Heavy              Daily         Normal            Normal          Low  63.0  23.7       100.0          7.3              165.1            NaN            Yes     Yes
14    Other      No                 NaN              Never            Low        Borderline         High  42.0  30.5        88.0          7.7              183.4        Regular             No      No
15     Male      No                 NaN              Never         Normal            Normal          Low  16.0  28.6        86.0          8.4               82.7            NaN            Yes     Yes
16    Other      No            Moderate             Rarely         Normal            Normal         High  58.0  18.1        99.0          6.9              126.7        Regular            Yes      No
17     Male     NaN            Moderate              Often            Low        Borderline         High  22.0  22.2        83.0          7.5              195.1        Regular            Yes      No
18   Female     Yes                 NaN              Daily         Normal        Borderline         High   6.0  21.0        82.0          3.1              178.4            NaN             No      No
19   Female     Yes            Moderate             Rarely         Normal        Borderline         High  43.0  20.3        80.0          4.1              133.7            NaN             No     Yes
20   Female     Yes                 NaN              Never           High        Borderline       Medium  52.0  25.3       103.0          9.9              169.1            NaN             No      No
21   Female      No               Heavy              Daily         Normal              High         High  70.0  32.6        93.0          3.5              178.3     Occasional             No     Yes
22    Other      No            Moderate              Never           High              High          Low  78.0  20.4        83.0          7.8              115.2        Regular            Yes      No
23     Male     Yes                 NaN              Often            Low        Borderline       Medium  33.0  24.2       111.0          4.2              186.0        Regular            Yes      No
24     Male      No            Moderate             Rarely            Low            Normal       Medium  45.0  24.8        72.0          8.0              131.2     Occasional             No      No
25    Other      No                 NaN              Often           High        Borderline         High  67.0  39.4        95.0          7.9              138.6        Regular             No      No
26     Male      No                 NaN             Rarely            Low        Borderline       Medium  77.0  38.9       105.0          4.6              200.0        Regular             No      No
27   Female     Yes            Moderate              Never         Normal            Normal         High  77.0  35.0        56.0          4.9              179.6            NaN             No      No
28     Male     Yes               Heavy              Often         Normal              High          Low  15.0  21.0       110.0          7.6              117.0     Occasional            Yes      No
29   Female     Yes                 NaN              Often         Normal        Borderline         High  70.0  16.7        52.0          5.7               71.3            NaN             No      No
30    Other      No                 NaN              Never            Low        Borderline       Medium  95.0  22.9        87.0          4.4              151.4     Occasional            Yes     Yes
31     Male     Yes                 NaN              Often         Normal              High          Low  18.0  21.7        83.0          8.1              161.5            NaN             No     Yes
32    Other     Yes               Heavy              Daily            Low              High         High   1.0  27.6        93.0          4.1              154.6        Regular             No      No
33     Male     Yes               Heavy             Rarely         Normal            Normal          Low   9.0  34.4        79.0          9.0              195.8     Occasional             No      No
34   Female     Yes            Moderate             Rarely           High              High          Low  49.0  36.5        66.0          6.6              182.2     Occasional            Yes      No
35    Other     Yes               Heavy             Rarely            Low              High       Medium  80.0  36.1       108.0          3.7              128.3            NaN             No     Yes
36     Male     Yes            Moderate              Daily            Low              High          Low  11.0  24.0        59.0          7.9               78.2     Occasional            Yes      No
37   Female      No            Moderate             Rarely         Normal            Normal       Medium  69.0  32.2        67.0          6.6              131.9        Regular            Yes     Yes
38    Other      No               Heavy              Never            Low              High          Low  21.0  22.8        94.0          5.1              159.6        Regular             No     Yes
39    Other     Yes            Moderate              Often            Low              High         High  31.0  16.5       108.0          6.0              149.0        Regular            Yes     Yes
40     Male     Yes               Heavy              Daily           High            Normal          Low  83.0  32.5       111.0          5.1              140.0            NaN            Yes     Yes
41     Male      No            Moderate             Rarely           High              High         High   0.0  15.2       108.0          4.8                NaN     Occasional            Yes     Yes
42     Male      No               Heavy              Never         Normal              High         High  53.0  25.2        98.0          4.1              108.2            NaN             No      No
43   Female     Yes               Heavy              Often           High            Normal          Low  57.0  23.2       112.0          5.5              106.1        Regular            Yes      No
44     Male     Yes            Moderate              Often         Normal        Borderline         High  69.0  32.3        81.0          4.8              135.0     Occasional            Yes      No
45    Other     Yes                 NaN              Daily         Normal            Normal          Low  82.0  34.2        59.0          7.8               90.9        Regular             No      No
46    Other     Yes            Moderate              Daily         Normal              High          Low  17.0  22.6        60.0          7.8              114.3     Occasional             No      No
47     Male      No               Heavy              Daily            Low              High         High   5.0  35.3       119.0          6.5              112.1     Occasional            Yes     Yes
48     Male     Yes                 NaN              Never           High              High         High  44.0  22.3       111.0          8.4              146.3            NaN            Yes      No
49    Other     Yes            Moderate              Never         Normal            Normal       Medium  96.0  26.2        96.0          8.9               78.7     Occasional            Yes      No
50   Female     Yes            Moderate              Daily           High              High         High  22.0  33.2        83.0          7.1              177.9        Regular            Yes     Yes
51     Male     Yes            Moderate             Rarely         Normal              High       Medium  22.0  32.3        66.0          7.3              143.1     Occasional             No      No
52     Male      No                 NaN              Often           High            Normal         High  25.0  39.7       103.0          5.0              157.2        Regular             No     Yes
53    Other      No               Heavy              Often           High        Borderline          Low  76.0  20.6        89.0          9.3              161.4            NaN            Yes      No
54     Male      No            Moderate              Never         Normal        Borderline         High   6.0  31.6        68.0          3.2              107.9        Regular             No     Yes
55   Female     Yes            Moderate              Often            Low              High          Low  78.0  30.2       116.0          5.4              131.1     Occasional            Yes      No
56    Other     Yes            Moderate             Rarely           High            Normal          Low  43.0  37.9       102.0          8.1              194.3        Regular             No      No
57     Male      No            Moderate              Often            Low              High          Low  26.0  18.9       113.0          3.6              169.7        Regular             No     Yes
58    Other     Yes            Moderate              Never            Low            Normal       Medium  25.0  33.8        96.0          4.3              196.0     Occasional            Yes     Yes
59     Male     Yes               Heavy              Never         Normal            Normal         High  96.0  29.2        55.0          7.1              167.0        Regular            Yes     Yes
60     Male      No               Heavy             Rarely         Normal        Borderline          Low  78.0  21.9        65.0          6.9               92.8     Occasional            Yes     Yes
61     Male      No            Moderate             Rarely         Normal        Borderline          Low  35.0  26.9        67.0          8.2               78.4            NaN            Yes     Yes
62   Female      No                 NaN              Often           High            Normal       Medium  54.0  23.3       101.0          8.7              145.1        Regular             No     Yes
63   Female      No               Heavy              Often         Normal              High         High  63.0  29.5        97.0          3.9              116.5            NaN             No     Yes
64    Other     Yes                 NaN              Never         Normal        Borderline         High  90.0  37.2        92.0          3.1              105.8        Regular            Yes     Yes
65     Male     Yes               Heavy             Rarely           High              High       Medium  56.0  29.2        88.0          7.8              174.9        Regular             No      No
66     Male      No            Moderate             Rarely           High        Borderline       Medium  68.0  30.8        98.0          5.1              117.7            NaN             No      No
67   Female     Yes               Heavy             Rarely         Normal        Borderline         High  60.0  28.0        61.0          7.4              111.2        Regular            Yes     Yes
68     Male      No            Moderate              Often         Normal              High       Medium   1.0  16.3        59.0          4.1              180.5        Regular            Yes      No
69   Female      No               Heavy             Rarely         Normal        Borderline         High  54.0  20.8       104.0          6.3              180.0            NaN             No      No
70     Male     Yes            Moderate              Never         Normal        Borderline         High  96.0  27.3        50.0          6.5              116.3        Regular            Yes      No
71    Other      No            Moderate              Never            Low              High          Low  79.0  22.8        98.0          7.1              178.2     Occasional            Yes      No
72     Male     Yes            Moderate              Often            Low        Borderline          Low  86.0  19.5        85.0          6.6              180.6        Regular             No     Yes
73     Male     Yes            Moderate              Daily         Normal        Borderline         High  37.0  27.6        70.0          6.5              125.1        Regular             No      No
74   Female     Yes                 NaN              Often            Low        Borderline         High  79.0  23.1        86.0          5.3               78.6        Regular            Yes     Yes
75     Male     Yes            Moderate              Daily           High              High         High  77.0  21.5        73.0          3.5               70.2            NaN             No      No
76     Male      No                 NaN             Rarely            Low            Normal         High  28.0  26.6       104.0          3.6              138.0     Occasional            Yes      No
77   Female     Yes                 NaN              Often            Low              High         High  25.0  18.3        74.0          6.0              114.7     Occasional            Yes      No
78    Other      No            Moderate              Never         Normal            Normal         High  34.0  38.2        56.0          5.5              199.6        Regular             No     Yes
79    Other      No                 NaN             Rarely            Low        Borderline       Medium  78.0  36.7        73.0          6.6              170.4            NaN             No      No
80   Female      No               Heavy              Never            Low            Normal         High  66.0  32.7        60.0          5.1              169.0            NaN            Yes     Yes
81   Female      No            Moderate             Rarely            Low              High       Medium  86.0  17.7        61.0          7.8              194.2     Occasional            Yes      No
82   Female     Yes                 NaN              Often            Low              High       Medium  28.0  34.4        84.0          9.0              185.4            NaN            Yes     Yes
83   Female     Yes            Moderate              Daily           High        Borderline         High  33.0  35.2       112.0          5.1              111.4        Regular             No      No
84   Female      No            Moderate             Rarely         Normal            Normal         High  96.0  34.2       117.0          4.4               91.6        Regular            NaN     Yes
85    Other      No            Moderate              Daily         Normal        Borderline       Medium  40.0  17.8       106.0          3.8              167.0            NaN             No     Yes
86    Other     Yes                 NaN             Rarely           High        Borderline       Medium  40.0  31.1        62.0          7.3              119.2        Regular            Yes      No
87   Female      No               Heavy              Never            Low              High         High  22.0  35.9        72.0          6.1              131.5     Occasional             No     Yes
88     Male     Yes               Heavy              Never           High            Normal         High  70.0  29.4        88.0          4.3              152.0        Regular            Yes      No
89   Female      No                 NaN             Rarely            Low            Normal       Medium   2.0  31.2        61.0          7.6              188.0            NaN             No      No
90     Male     Yes            Moderate              Daily           High            Normal       Medium  57.0  26.5        83.0          4.0              124.5            NaN            Yes      No
91   Female      No                 NaN              Often         Normal            Normal       Medium  31.0  28.2        80.0          6.9              171.8        Regular            Yes      No
92   Female      No                 NaN              Often         Normal        Borderline          Low  30.0  15.9       111.0          6.7              104.9     Occasional            Yes      No
93    Other     Yes                 NaN              Never         Normal        Borderline       Medium  81.0  31.0        62.0          8.1              160.7            NaN            Yes      No
94     Male      No            Moderate              Often            Low              High          Low  42.0  17.0        80.0          3.4               70.2        Regular             No      No
95     Male      No                 NaN              Never            Low        Borderline         High   6.0  25.9        51.0          9.2              183.3        Regular             No      No
96    Other     Yes            Moderate              Often           High        Borderline         High   0.0  22.3        64.0          7.9               73.9     Occasional             No      No
97    Other      No                 NaN             Rarely           High              High       Medium  60.0  28.6       106.0          4.5              162.7        Regular             No      No
98    Other     Yes               Heavy              Never         Normal              High         High  13.0  18.3        83.0          4.3               76.0        Regular             No      No

In [15]:
# convert empty cells and spaces into NaN
health_dataset_1 = health_dataset_1.replace("", np.nan)
health_dataset_1 = health_dataset_1.replace(" ", np.nan)

In [16]:
# numerical column null value replace by mean /median

health_dataset_1["Age"] = health_dataset_1["Age"].fillna(health_dataset_1["Age"].median())


health_dataset_1["BMI"] = health_dataset_1["BMI"].fillna(health_dataset_1["BMI"].mean())


health_dataset_1["Heart_Rate"] = health_dataset_1["Heart_Rate"].fillna(health_dataset_1["Heart_Rate"].mean())


health_dataset_1["Sleep_Hours"] = health_dataset_1["Sleep_Hours"].fillna(health_dataset_1["Sleep_Hours"].mean())


health_dataset_1["Blood_Sugar_Level"] = health_dataset_1["Blood_Sugar_Level"].fillna(health_dataset_1["Blood_Sugar_Level"].median())

In [17]:
# categorial column null value replace by mode

health_dataset_1["Gender"] = health_dataset_1["Gender"].fillna(health_dataset_1["Gender"].mode()[0])

health_dataset_1["Smoking"] = health_dataset_1["Smoking"].fillna(health_dataset_1["Smoking"].mode()[0])

health_dataset_1["Alcohol_Consumption"] = health_dataset_1["Alcohol_Consumption"].fillna(health_dataset_1["Alcohol_Consumption"].mode()[0])

health_dataset_1["Exercise_Frequency"] = health_dataset_1["Exercise_Frequency"].fillna(health_dataset_1["Exercise_Frequency"].mode()[0])

health_dataset_1["Blood_Pressure"] = health_dataset_1["Blood_Pressure"].fillna(health_dataset_1["Blood_Pressure"].mode()[0])

health_dataset_1["Cholesterol_Level"] = health_dataset_1["Cholesterol_Level"].fillna(health_dataset_1["Cholesterol_Level"].mode()[0])

health_dataset_1["Stress_Level"] = health_dataset_1["Stress_Level"].fillna(health_dataset_1["Stress_Level"].mode()[0])

health_dataset_1["Medication_Use"] = health_dataset_1["Medication_Use"].fillna(health_dataset_1["Medication_Use"].mode()[0])

health_dataset_1["Family_History"] = health_dataset_1["Family_History"].fillna(health_dataset_1["Family_History"].mode()[0])

In [18]:
#check again have any null value ar not 
health_dataset_1.isna().sum()

Gender                 0
Smoking                0
Alcohol_Consumption    0
Exercise_Frequency     0
Blood_Pressure         0
Cholesterol_Level      0
Stress_Level           0
Age                    0
BMI                    0
Heart_Rate             0
Sleep_Hours            0
Blood_Sugar_Level      0
Medication_Use         0
Family_History         0
Illness                0
dtype: int64

In [19]:
print(health_dataset_1.to_string())

     Gender Smoking Alcohol_Consumption Exercise_Frequency Blood_Pressure Cholesterol_Level Stress_Level   Age        BMI  Heart_Rate  Sleep_Hours  Blood_Sugar_Level Medication_Use Family_History Illness
0    Female      No            Moderate              Never         Normal        Borderline         High  90.0  16.600000  119.000000     3.600000              143.6     Occasional             No     Yes
1     Other     Yes            Moderate              Never         Normal            Normal          Low  20.0  29.900000   69.000000     9.900000              121.8     Occasional            Yes      No
2      Male     Yes               Heavy              Daily           High              High          Low  52.0  33.500000   54.000000     8.500000              107.0     Occasional            Yes     Yes
3      Male     Yes               Heavy              Daily         Normal              High          Low  15.0  20.300000   72.000000     9.500000               92.1     Occasional             No     Yes
4      Male      No            Moderate              Often           High              High       Medium  60.0  36.000000   58.000000     4.400000              113.6     Occasional             No     Yes
5      Male      No            Moderate              Daily            Low              High         High  53.0  15.800000  107.000000     9.700000              149.0     Occasional             No      No
6      Male     Yes            Moderate              Daily            Low        Borderline          Low  39.0  36.100000  108.000000     4.000000              144.9     Occasional            Yes     Yes
7      Male      No            Moderate              Daily         Normal        Borderline         High  25.0  26.500000  103.000000     6.600000               91.3     Occasional            Yes     Yes
8      Male      No            Moderate              Never           High        Borderline       Medium  79.0  20.400000   95.000000     8.800000               86.2     Occasional             No     Yes
9    Female     Yes            Moderate              Never           High              High       Medium  91.0  18.300000   71.000000     5.400000               73.5        Regular             No      No
10    Other     Yes            Moderate              Never            Low        Borderline          Low  64.0  38.800000  113.000000     6.000000               71.6     Occasional            Yes     Yes
11     Male      No            Moderate              Daily            Low        Borderline          Low  99.0  16.800000   57.000000     3.900000              184.4        Regular             No     Yes
12   Female     Yes            Moderate              Never           High            Normal         High  73.0  20.000000   69.000000     3.900000               75.9     Occasional             No     Yes
13   Female      No               Heavy              Daily         Normal            Normal          Low  63.0  23.700000  100.000000     7.300000              165.1     Occasional            Yes     Yes
14    Other      No            Moderate              Never            Low        Borderline         High  42.0  30.500000   88.000000     7.700000              183.4        Regular             No      No
15     Male      No            Moderate              Never         Normal            Normal          Low  16.0  28.600000   86.000000     8.400000               82.7     Occasional            Yes     Yes
16    Other      No            Moderate             Rarely         Normal            Normal         High  58.0  18.100000   99.000000     6.900000              126.7        Regular            Yes      No
17     Male      No            Moderate              Often            Low        Borderline         High  22.0  22.200000   83.000000     7.500000              195.1        Regular            Yes      No
18   Female     Yes            Moderate              Daily         Normal        Borderline         High   6.0  21.000000   82.000000     3.100000              178.4     Occasional             No      No
19   Female     Yes            Moderate             Rarely         Normal        Borderline         High  43.0  20.300000   80.000000     4.100000              133.7     Occasional             No     Yes
20   Female     Yes            Moderate              Never           High        Borderline       Medium  52.0  25.300000  103.000000     9.900000              169.1     Occasional             No      No
21   Female      No               Heavy              Daily         Normal              High         High  70.0  32.600000   93.000000     3.500000              178.3     Occasional             No     Yes
22    Other      No            Moderate              Never           High              High          Low  78.0  20.400000   83.000000     7.800000              115.2        Regular            Yes      No
23     Male     Yes            Moderate              Often            Low        Borderline       Medium  33.0  24.200000  111.000000     4.200000              186.0        Regular            Yes      No
24     Male      No            Moderate             Rarely            Low            Normal       Medium  45.0  24.800000   72.000000     8.000000              131.2     Occasional             No      No
25    Other      No            Moderate              Often           High        Borderline         High  67.0  39.400000   95.000000     7.900000              138.6        Regular             No      No
26     Male      No            Moderate             Rarely            Low        Borderline       Medium  77.0  38.900000  105.000000     4.600000              200.0        Regular             No      No
27   Female     Yes            Moderate              Never         Normal            Normal         High  77.0  35.000000   56.000000     4.900000              179.6     Occasional             No      No
28     Male     Yes               Heavy              Often         Normal              High          Low  15.0  21.000000  110.000000     7.600000              117.0     Occasional            Yes      No
29   Female     Yes            Moderate              Often         Normal        Borderline         High  70.0  16.700000   52.000000     5.700000               71.3     Occasional             No      No
30    Other      No            Moderate              Never            Low        Borderline       Medium  95.0  22.900000   87.000000     4.400000              151.4     Occasional            Yes     Yes
31     Male     Yes            Moderate              Often         Normal              High          Low  18.0  21.700000   83.000000     8.100000              161.5     Occasional             No     Yes
32    Other     Yes               Heavy              Daily            Low              High         High   1.0  27.600000   93.000000     4.100000              154.6        Regular             No      No
33     Male     Yes               Heavy             Rarely         Normal            Normal          Low   9.0  34.400000   79.000000     9.000000              195.8     Occasional             No      No
34   Female     Yes            Moderate             Rarely           High              High          Low  49.0  36.500000   66.000000     6.600000              182.2     Occasional            Yes      No
35    Other     Yes               Heavy             Rarely            Low              High       Medium  80.0  36.100000  108.000000     3.700000              128.3     Occasional             No     Yes
36     Male     Yes            Moderate              Daily            Low              High          Low  11.0  24.000000   59.000000     7.900000               78.2     Occasional            Yes      No
37   Female      No            Moderate             Rarely         Normal            Normal       Medium  69.0  32.200000   67.000000     6.600000              131.9        Regular            Yes     Yes
38    Other      No               Heavy              Never            Low              High          Low  21.0  22.800000   94.000000     5.100000              159.6        Regular             No     Yes
39    Other     Yes            Moderate              Often            Low              High         High  31.0  16.500000  108.000000     6.000000              149.0        Regular            Yes     Yes
40     Male     Yes               Heavy              Daily           High            Normal          Low  83.0  32.500000  111.000000     5.100000              140.0     Occasional            Yes     Yes
41     Male      No            Moderate             Rarely           High              High         High   0.0  15.200000  108.000000     4.800000              136.3     Occasional            Yes     Yes
42     Male      No               Heavy              Never         Normal              High         High  53.0  25.200000   98.000000     4.100000              108.2     Occasional             No      No
43   Female     Yes               Heavy              Often           High            Normal          Low  57.0  23.200000  112.000000     5.500000              106.1        Regular            Yes      No
44     Male     Yes            Moderate              Often         Normal        Borderline         High  69.0  32.300000   81.000000     4.800000              135.0     Occasional            Yes      No
45    Other     Yes            Moderate              Daily         Normal            Normal          Low  82.0  34.200000   59.000000     7.800000               90.9        Regular             No      No
46    Other     Yes            Moderate              Daily         Normal              High          Low  17.0  22.600000   60.000000     7.800000              114.3     Occasional             No      No
47     Male      No               Heavy              Daily            Low              High         High   5.0  35.300000  119.000000     6.500000              112.1     Occasional            Yes     Yes
48     Male     Yes            Moderate              Never           High              High         High  44.0  22.300000  111.000000     8.400000              146.3     Occasional            Yes      No
49    Other     Yes            Moderate              Never         Normal            Normal       Medium  96.0  26.200000   96.000000     8.900000               78.7     Occasional            Yes      No
50   Female     Yes            Moderate              Daily           High              High         High  22.0  33.200000   83.000000     7.100000              177.9        Regular            Yes     Yes
51     Male     Yes            Moderate             Rarely         Normal              High       Medium  22.0  32.300000   66.000000     7.300000              143.1     Occasional             No      No
52     Male      No            Moderate              Often           High            Normal         High  25.0  39.700000  103.000000     5.000000              157.2        Regular             No     Yes
53    Other      No               Heavy              Often           High        Borderline          Low  76.0  20.600000   89.000000     9.300000              161.4     Occasional            Yes      No
54     Male      No            Moderate              Never         Normal        Borderline         High   6.0  31.600000   68.000000     3.200000              107.9        Regular             No     Yes
55   Female     Yes            Moderate              Often            Low              High          Low  78.0  30.200000  116.000000     5.400000              131.1     Occasional            Yes      No
56    Other     Yes            Moderate             Rarely           High            Normal          Low  43.0  37.900000  102.000000     8.100000              194.3        Regular             No      No
57     Male      No            Moderate              Often            Low              High          Low  26.0  18.900000  113.000000     3.600000              169.7        Regular             No     Yes
58    Other     Yes            Moderate              Never            Low            Normal       Medium  25.0  33.800000   96.000000     4.300000              196.0     Occasional            Yes     Yes
59     Male     Yes               Heavy              Never         Normal            Normal         High  96.0  29.200000   55.000000     7.100000              167.0        Regular            Yes     Yes
60     Male      No               Heavy             Rarely         Normal        Borderline          Low  78.0  21.900000   65.000000     6.900000               92.8     Occasional            Yes     Yes
61     Male      No            Moderate             Rarely         Normal        Borderline          Low  35.0  26.900000   67.000000     8.200000               78.4     Occasional            Yes     Yes
62   Female      No            Moderate              Often           High            Normal       Medium  54.0  23.300000  101.000000     8.700000              145.1        Regular             No     Yes
63   Female      No               Heavy              Often         Normal              High         High  63.0  29.500000   97.000000     3.900000              116.5     Occasional             No     Yes
64    Other     Yes            Moderate              Never         Normal        Borderline         High  90.0  37.200000   92.000000     3.100000              105.8        Regular            Yes     Yes
65     Male     Yes               Heavy             Rarely           High              High       Medium  56.0  29.200000   88.000000     7.800000              174.9        Regular             No      No
66     Male      No            Moderate             Rarely           High        Borderline       Medium  68.0  30.800000   98.000000     5.100000              117.7     Occasional             No      No
67   Female     Yes               Heavy             Rarely         Normal        Borderline         High  60.0  28.000000   61.000000     7.400000              111.2        Regular            Yes     Yes
68     Male      No            Moderate              Often         Normal              High       Medium   1.0  16.300000   59.000000     4.100000              180.5        Regular            Yes      No
69   Female      No               Heavy             Rarely         Normal        Borderline         High  54.0  20.800000  104.000000     6.300000              180.0     Occasional             No      No
70     Male     Yes            Moderate              Never         Normal        Borderline         High  96.0  27.300000   50.000000     6.500000              116.3        Regular            Yes      No
71    Other      No            Moderate              Never            Low              High          Low  79.0  22.800000   98.000000     7.100000              178.2     Occasional            Yes      No
72     Male     Yes            Moderate              Often            Low        Borderline          Low  86.0  19.500000   85.000000     6.600000              180.6        Regular             No     Yes
73     Male     Yes            Moderate              Daily         Normal        Borderline         High  37.0  27.600000   70.000000     6.500000              125.1        Regular             No      No
74   Female     Yes            Moderate              Often            Low        Borderline         High  79.0  23.100000   86.000000     5.300000               78.6        Regular            Yes     Yes
75     Male     Yes            Moderate              Daily           High              High         High  77.0  21.500000   73.000000     3.500000               70.2     Occasional             No      No
76     Male      No            Moderate             Rarely            Low            Normal         High  28.0  26.600000  104.000000     3.600000              138.0     Occasional            Yes      No
77   Female     Yes            Moderate              Often            Low              High         High  25.0  18.300000   74.000000     6.000000              114.7     Occasional            Yes      No
78    Other      No            Moderate              Never         Normal            Normal         High  34.0  38.200000   56.000000     5.500000              199.6        Regular             No     Yes
79    Other      No            Moderate             Rarely            Low        Borderline       Medium  78.0  36.700000   73.000000     6.600000              170.4     Occasional             No      No
80   Female      No               Heavy              Never            Low            Normal         High  66.0  32.700000   60.000000     5.100000              169.0     Occasional            Yes     Yes
81   Female      No            Moderate             Rarely            Low              High       Medium  86.0  17.700000   61.000000     7.800000              194.2     Occasional            Yes      No
82   Female     Yes            Moderate              Often            Low              High       Medium  28.0  34.400000   84.000000     9.000000              185.4     Occasional            Yes     Yes
83   Female     Yes            Moderate              Daily           High        Borderline         High  33.0  35.200000  112.000000     5.100000              111.4        Regular             No      No
84   Female      No            Moderate             Rarely         Normal            Normal         High  96.0  34.200000  117.000000     4.400000               91.6        Regular             No     Yes
85    Other      No            Moderate              Daily         Normal        Borderline       Medium  40.0  17.800000  106.000000     3.800000              167.0     Occasional             No     Yes
86    Other     Yes            Moderate             Rarely           High        Borderline       Medium  40.0  31.100000   62.000000     7.300000              119.2        Regular            Yes      No
87   Female      No               Heavy              Never            Low              High         High  22.0  35.900000   72.000000     6.100000              131.5     Occasional             No     Yes
88     Male     Yes               Heavy              Never           High            Normal         High  70.0  29.400000   88.000000     4.300000              152.0        Regular            Yes      No
89   Female      No            Moderate             Rarely            Low            Normal       Medium   2.0  31.200000   61.000000     7.600000              188.0     Occasional             No      No
90     Male     Yes            Moderate              Daily           High            Normal       Medium  57.0  26.500000   83.000000     4.000000              124.5     Occasional            Yes      No
91   Female      No            Moderate              Often         Normal            Normal       Medium  31.0  28.200000   80.000000     6.900000              171.8        Regular            Yes      No
92   Female      No            Moderate              Often         Normal        Borderline          Low  30.0  15.900000  111.000000     6.700000              104.9     Occasional            Yes      No
93    Other     Yes            Moderate              Never         Normal        Borderline       Medium  81.0  31.000000   62.000000     8.100000              160.7     Occasional            Yes      No
94     Male      No            Moderate              Often            Low              High          Low  42.0  17.000000   80.000000     3.400000               70.2        Regular             No      No
95     Male      No            Moderate              Never            Low        Borderline         High   6.0  25.900000   51.000000     9.200000              183.3        Regular             No      No
96    Other     Yes            Moderate              Often           High        Borderline         High   0.0  22.300000   64.000000     7.900000               73.9     Occasional             No      No

In [20]:
#now my dataset is ready for encoding 
print(health_dataset_1.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               1000 non-null   str
 1   Smoking              1000 non-null   str
 2   Alcohol_Consumption  1000 non-null   str
 3   Exercise_Frequency   1000 non-null   str
 4   Blood_Pressure       1000 non-null   str
 5   Cholesterol_Level    1000 non-null   str
 6   Stress_Level         1000 non-null   str
 7   Age                  1000 non-null   float64
 8   BMI                  1000 non-null   float64
 9   Heart_Rate           1000 non-null   float64
 10  Sleep_Hours          1000 non-null   float64
 11  Blood_Sugar_Level    1000 non-null   float64
 12  Medication_Use       1000 non-null   str
 13  Family_History       1000 non-null   str
 14  Illness              1000 non-null   str
dtypes: float64(5), str(10)
memory usage: 117.3 KB
None

In [21]:
#convert new clean dataset in csv format  
health_dataset_1.to_csv("clean_health_dataset.csv", index=False)